### PR TITLE
Behavior should be saved as native strings

### LINKED ISSUE #296: Behavior should be saved as native strings
See https://github.com/plone/Products.CMFPlone/issues/2881

Fixes https://github.com/plone/Products.CMFPlone/issues/2881

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #296
Closes plone/Products.CMFPlone#2881

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
I think the increased test coverage exposes a problem that was masked by this commit https://github.com/plone/plone.app.dexterity/commit/2e32188c5b5a6de52b641455abe94e01384bf704

@iham do you remember why you had to change it?

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Thanks @thet for picking this :) 
I would revert b09e3a9 to make the test pass also on 5.1 (which is missing safe_nativestring).
Another option is to declare that this package is 5.2 only, but I do not think it is desiderable for this small PR.

**Comment by thet** [comment]
@ale-rt i thought this is 5.2 only, but apparently it isn't. i removed the commit.

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
5.1 failure is the usual robot test prob. I merge...

**Comment by ale-rt** [comment]
Thanks!

**Pull request merged**
