### PR TITLE
Fix the constraint types mode calculation

### LINKED ISSUE #319: plone.constraintypes breaks when the parent as no portal type
I found this when working on https://github.com/plone/Products.CMFPlone/issues/2454:
```
  File "/home/ale/.buildout/eggs/plone.app.dexterity-2.6.8-py3.8.egg/plone/app/dexterity/behaviors/constrains.py", line 30, in getConstrainTypesMode
    if not self.context.portal_type == parent.portal_type:
AttributeError: 'RequestContainer' object has no attribute 'portal_type'
```
I would say:
1. we should not lookup portal_type in an acquired object
2. we should use getattr to check for the portal type

### PR DESCRIPTION
**Pull request by ale-rt**
Fix the constraint types mode calculation, disabling acquisition and gracefully checking for the existence of a portal type attribute in the container

Fixes #319

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
While this is necessary to have the behavior working on the Plone site object, I think the patch is right even for existing web site.
Let's see if jenkins shows me something that I am missing.

**Comment by jaroel** [comment]
@ale-rt could you please verify that the tests are correct?
If so, then lgtm and we can merge this.

**Review by mauritsvanrees — APPROVED** [review]
Seems an obviously good fix, and fine for 5.2 and 6.0. LGTM.

One small thing: the news snippet must be named `319.bugfix`. Can be fixed after merge too.

**Comment by jaroel** [comment]
@mauritsvanrees I've renamed 319.fixed to 319.bugfix.
Please merge at your leisure.

**Comment by mauritsvanrees** [comment]
Please start the tests on Jenkins:

- Log in to [jenkins.plone.org](https://jenkins.plone.org) with your github account.
- Go to the 'Build with parameters' form for all relevant Plone versions. You should see direct links to those versions under the 'Some checks haven’t completed yet' box of the pull request.
- Paste the pull request url in that form and build it.

**Comment by mauritsvanrees** [comment]
I meant to paste a different automatic reply:

@jenkins-plone-org please run jobs

**Review by ale-rt — COMMENTED** [review]
Very good! Thanks for improving the coverage :)

**Pull request merged**
