### PR TITLE
Rename 'Dexterity Content Types' to 'Content Types'

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Makes sense.
Needs updates in documentation, later.
And an upgrade step.

**Comment by tisto** [comment]
@mauritsvanrees thanks for the review. Yeah, that's the first step. I am aware that more is needed here. Help is always welcome! :)

**Comment by tisto** [comment]
@mauritsvanrees where would we add the upgrade step? In plone.app.dexterity or CMFPlone?

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I was going to say plone.app.upgrade, because p.a.dexterity has no upgrades, but I was wrong.

**Comment by jensens** [comment]
> I was going to say plone.app.upgrade, because p.a.dexterity has no upgrades, but I was wrong.

But anyway it would need to be called from p.a.upgrade.

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
> > I was going to say plone.app.upgrade, because p.a.dexterity has no upgrades, but I was wrong.
> 
> But anyway it would need to be called from p.a.upgrade.

Not needed: upgrade steps from `plone.app.dexterity` are automatically applied at the end of [`@@plone-upgrade`](https://github.com/plone/Products.CMFPlone/blob/adbd2c05350d4a3ffa0d82d12d45913e97537eac/Products/CMFPlone/MigrationTool.py#L101).

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
