### PR TITLE
Rename 'Dexterity Content Types' to just 'Content Types'

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]
Definitely a good idea!

**Comment by jensens** [comment]
+1000 

@tisto did you check if in CMFPlone are traces left too?

**Comment by ale-rt** [comment]
I think a PR for plone.app.locales to fix the changed message id might be a good idea.

**Comment by ale-rt** [comment]
Also this one should be changed https://github.com/plone/plone.app.dexterity/blob/0afaa5cd727cdad5e23ce1e7d7dc8f60f5553b06/plone/app/dexterity/profiles/default/controlpanel.xml#L9 (and an upgrade step is needed).

LOL! You thought it was easy ;)

**Comment by tisto** [comment]
@ale-rt yeah! I was wondering if it might be easier to just change stuff in plone.app.locales and keep the original string.

**Comment by tisto** [comment]
@jensens @ale-rt @erral I created a "lightweight" version of this rename in p.a.locales:

https://github.com/collective/plone.app.locales/pull/337

How would we approach this in general? Do a PR in plone.app.dexterity first, merge it. Then fix things in p.a.locales afterwards?

**Comment by jensens** [comment]
> How would we approach this in general? Do a PR in plone.app.dexterity first, merge it. Then fix things in p.a.locales afterwards?

Yes, I think in this order.

**Pull request merged**
