### PR TITLE
Overhaul of chapter form-schema-hints.rst

### PR DESCRIPTION
**Pull request by jensens**
- fixed: historic and confusing ``... import directives as from`` changed.
- fixed: wrong usage of ``primary`` and ``fieldset`` corrected.
- overhaul: introduction
- overhaul: table style 
- overhaul: code style

/cc @svx @polyester may you have a quick look?

### CODE REVIEW

**Comment by svx** [comment]
@jensens great cool, thanks ! There are some typos and the way how links are used are not ideal, because separating the link and the link-target makes it hard to translate :) :

```
.. _plone.autoform: http://pypi.python.org/pypi/plone.autoform
 ```

More info is here: http://www.sphinx-doc.org/en/stable/rest.html#hyperlinks

Should I fix it, or you want to do it ?

**Comment by jensens** [comment]
ok, if you have a free slow, otherwise i can do it later.

**Comment by svx** [comment]
OK I am on it now !

**Comment by svx** [comment]
@jensens done ! please review !

**Comment by jensens** [comment]
Great, thanks. All fine.

**Comment by svx** [comment]
OK should I merge ?

**Comment by jensens** [comment]
usually i dont merge my own branches, so, yes please

**Comment by svx** [comment]
yes, I was not sure because I contributed to this PR, but OK her we go !

**Comment by svx** [comment]
Will be available on docs.plone.org upcoming Friday

**Pull request merged**
