### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by ebrehault**
related to https://github.com/plone/plone.schemaeditor/pull/26

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/44/

**Comment by tisto** [comment]
@ebrehault There is a test failure:

http://jenkins.plone.org/job/pull-request-5.0/44/testReport/junit/plone.app.dexterity/tests/editing_txt/

Does this pr depend on a change in another package?

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/49/

**Comment by tisto** [comment]
Job still fails...

**Comment by ebrehault** [comment]
@tisto yes it depends on https://github.com/plone/plone.schemaeditor/pull/26
so as discussed there https://github.com/plone/plone.schemaeditor/pull/26#issuecomment-117992385 the proper test job is http://jenkins.plone.org/view/PLIPs/job/plip-13350-edit-member-schema-ttw
(but I need to merge CMFPlone with master as you said)

**Pull request merged**
