### PR TITLE
Fix for searchable Named(Blob)File

### PR DESCRIPTION
**Pull request by petschki**
see discussion https://community.plone.org/t/plone-6-installation-does-not-index-pdf-files/17056/11?u=petschki

### CODE REVIEW

**Comment by petschki** [comment]
waiting for #361 to be merged ... then I'll rebase this one. /cc @gforcada

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
pre-commit.ci autofix

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jensens I think the `pdftotext` binary is missing for this text and so the transform isn't registered. Can this be installed for the tests?

**Comment by jensens** [comment]
@gforcada is this possible to fix using meta or does it need manual work?

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
I changed the test strategy to check for the transform first ...

**Pull request merged**
