### PR TITLE
Issue 895 - Fix ace editor javascript reference

### PR DESCRIPTION
**Pull request by rodfersou**
closes https://github.com/plone/Products.CMFPlone/issues/895

### CODE REVIEW

**Comment by rodfersou** [comment]
Still need to fix ace-editor style to fill all the height 
ace-size-error

**Comment by rodfersou** [comment]
I changed the theme to the only disponible theme (monokai) and the height grows
ace-size-error2

**Comment by jensens** [comment]
test before failed because whole coredev failed, try again.
http://jenkins.plone.org/job/pull-request-5.0/345/

**Comment by rodfersou** [comment]
@pbauer jenkins still didn't give green light on this

**Pull request merged**
