### PR TITLE
Plone base overhaul

### PR DESCRIPTION
**Pull request by jensens**
- isort + black
- pyupgrade and six removal
- short name usage of behaviors in tests
- sleep in editing.rst reduced (saves 10sec in tests)
- use plone.base

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I review in the github app, where I cannot comment inline...

The code comment in the speedup commit now makes no sense anymore, so should be changed. Could be that the original comment was only ever true for PY2.

And I saw a zcml condition for Plone 51, maybe you could remove that as well, make it unconditional.

For the rest LGTM.

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
See comment.

**Comment by jensens** [comment]
Both corrected.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
