### PR TITLE
Revert "Revert "reflect moves from plone.app.widgets to plone.app.z3cform""

### PR DESCRIPTION
**Pull request by jensens**
Reverts plone/plone.app.dexterity#287

2nd trial...

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jensens Is this ready for merging together with https://github.com/plone/plone.app.vocabularies/pull/56, https://github.com/plone/plone.app.z3cform/pull/104 and https://github.com/plone/plone.app.widgets/pull/194?

**Comment by jensens** [comment]
@pbauer for Plone 5.2, yes. Since p.a.dexterity is on master for Plone 5.1 this needs to be tested.

**Comment by jensens** [comment]
@pbauer last commit should do it, I start the tests now.

**Pull request merged**
