### PR TITLE
Content types control panel: Show behavior name and interface.

### PR DESCRIPTION
**Pull request by ksuess**
Helps developer to find the code.

Fix https://github.com/plone/Products.CMFPlone/issues/3706

Page_—_Site

### CODE REVIEW

**Comment by ksuess** [comment]
Tests are OK (tox) locally.

But CI tests raise a *ComponentLookupError* for an ordinary plone.schema.JSONField.
Any hint is welcome.


```
      File "/home/runner/work/plone.app.dexterity/plone.app.dexterity/.tox/test/lib/python3.11/site-packages/plone/z3cform/layout.py", line 45, in update
        self.form_instance.update()
      File "/home/runner/work/plone.app.dexterity/plone.app.dexterity/.tox/test/lib/python3.11/site-packages/plone/z3cform/fieldsets/extensible.py", line 62, in update
        super().update()
      File "/home/runner/work/plone.app.dexterity/plone.app.dexterity/.tox/test/lib/python3.11/site-packages/plone/z3cform/patch.py", line 31, in GroupForm_update
        _original_GroupForm_update(self)
      File "/home/runner/work/plone.app.dexterity/plone.app.dexterity/.tox/test/lib/python3.11/site-packages/z3c/form/group.py", line 132, in update
        self.updateWidgets()
      File "/home/runner/work/plone.app.dexterity/plone.app.dexterity/.tox/test/lib/python3.11/site-packages/z3c/form/form.py", line 136, in updateWidgets
        self.widgets.update()
      File "/home/runner/work/plone.app.dexterity/plone.app.dexterity/.tox/test/lib/python3.11/site-packages/z3c/form/field.py", line 253, in update
        widget = zope.component.getMultiAdapter(
      File "/home/runner/work/plone.app.dexterity/plone.app.dexterity/.tox/test/lib/python3.11/site-packages/zope/component/_api.py", line 104, in getMultiAdapter
        raise ComponentLookupError(objects, interface, name)
    zope.interface.interfaces.ComponentLookupError: ((<plone.schema.jsonfield.JSONField object at 0x7f6dc35c4dd0 plone.dexterity.schema.generated.plone_5_1681896458_2_2634134_0_plonista.plone_schema_jsonfield_jsonfield>, <WSGIRequest, URL=None>), <InterfaceClass z3c.form.interfaces.IFieldWidget>, '')
```

See https://github.com/plone/plone.app.dexterity/actions/runs/4598445725/jobs/8419106105

**Comment by stevepiercy** [comment]
It looks like the tests in https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/tests/editing.rst need to be updated to align with the template changes.

**Comment by ksuess** [comment]
> It looks like the tests in https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/tests/editing.rst need to be updated to align with the template changes.

@stevepiercy dont't you think I have read the log? 
Your comment has the effect that I do not get any qualified feedback anymore.

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Pull request merged**
