### PR TITLE
Updated Form Schema Hints

### PR DESCRIPTION
**Pull request by ritwikagarwal**
Replaced IBasic.description with IDublinCore.description

### CODE REVIEW

**Comment by ritwikagarwal** [comment]
@jenkins-plone-org please run jobs

**Comment by ritwikagarwal** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
Why this change? `IDublinCore` inherits from `IBasic` so both are correct.

**Comment by jensens** [comment]
> Why this change? IDublinCore inherits from IBasic so both are correct.

IMO the problem is situated a bit deeper and more complex than it seems.

First, in the current way we use the composed ``plone.dublincore``  @ritwikagarwal is right. The matching is against the name w/o taking inheritance into account see 
https://github.com/plone/plone.autoform/blob/32a57ae42430aa6fe453d7d4befb69f84f0a45d8/plone/autoform/base.py#L166-L264

Second, we should really get rid of ``plone.dublincore`` and use all over the place the single atomic behaviors (`plone.basic`, `plone.categorization`, ...) which is out of scope here. I had a long discussion with @iham about this topic and we will propose a PLIP on this soon.

So I think the change is correct. 
@iham may you have a look here as well?

**Comment by jensens** [comment]
@ritwikagarwal in order to make this change ready for merge you need to document the changes. 

In short: Add a file ``news/293.bugfix`` (number of this PR dot one out of bugfix, feature, breaking). Write one or two line about your changes plus your ``[name]`` in brackets.

long read
https://community.plone.org/t/using-towncrier-for-changes-rst-in-plone-packages/6486

**Comment by ritwikagarwal** [comment]
@jensens  I was uesd to getting changes done in change.rst ,I have made a file in newslog though with this issue number but it is still not recorded in Changelog.Any ideas how to fix this?

**Comment by jensens** [comment]
@ritwikagarwal ok, I can not find any new file in https://github.com/plone/plone.app.dexterity/pull/294/files
Maybe a forgotten `git add` or so?

**Comment by ritwikagarwal** [comment]
@jenkins-plone-org please run jobs

**Comment by ritwikagarwal** [comment]
Thanks @jensens ,done .

**Pull request merged**
