### PR TITLE
Update tests to match `ignorePrefix = True` - refs #323

### PR DESCRIPTION
**Pull request by avoinea**
- See #323 and https://github.com/plone/plone.dexterity/pull/145

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Maybe try `form.widgets.IDublinCore.title` first, and fall back to `form.widgets.title` if not found. Or the other way around. Then the tests would pass with the current code and with your proposed fixes. This makes it easier to make the switch, if we choose so, without needing simultaneous PRs in ten or more packages.
But if we do this, I would say: only on master.

**Comment by avoinea** [comment]
@mauritsvanrees Switch PR to master and used a more generic getControl by labels. Let's see if it works.

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
@mauritsvanrees Hmm, the tests are for Plone 5.2. What am I missing here?

**Comment by mauritsvanrees** [comment]
When you keep the same PR but switch the target branch, the links to the Jenkins tests remain.
Maybe best to close this PR and create a new one.

**Pull request closed without merging**
