### PR TITLE
Use `INameFromTitle` interface from `plone.base`

### PR DESCRIPTION
**Pull request by gforcada**
This is part of https://github.com/plone/Products.CMFPlone/issues/3858

It needs https://github.com/plone/plone.base/pull/51 to be merged, _and released_.

It first needs #378 to be merged first.

See the tracking issue for the overview of the changes and why.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I have released a new `plone.base` version and updated the constraints at https://dist.plone.org/release/6.0-dev/ so should be fine now.
I will test this together with https://github.com/plone/plone.app.content/pull/271 on Jenkins.

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Failure seems related:

```
Failure in test test_add_item_w_title_only (plone.app.dexterity.behaviors.tests.test_id.TestShortNameBehavior.test_add_item_w_title_only)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.dexterity/plone/app/dexterity/behaviors/tests/test_id.py", line 58, in test_add_item_w_title_only
    self.assertEqual(self.browser.url, "http://nohost/plone/id-from-title")
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 1253, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 703, in fail
    raise self.failureException(msg)
AssertionError: 'http://nohost/plone/document' != 'http://nohost/plone/id-from-title'
- http://nohost/plone/document
?                       --  --
+ http://nohost/plone/id-from-title
?                     + +++  +++++
```

I did not dive in, and probably won't do that today.  @gforcada ?

**Comment by davisagli** [comment]
@mauritsvanrees @gforcada I tried to take a look at this, but the tests pass for me in buildout.coredev, and when I try `tox -e test` I get a different, bizarre error:
```
Test-module import failures:

Module: .tox.test.lib.python3.9.site-packages.plone.app.dexterity.behaviors.tests.test_contrains

ModuleNotFoundError: No module named '.tox'
```

**Comment by mauritsvanrees** [comment]
@davisagli The tests pass for me in coredev 6.1, but not in 6.0.
I have not seen the `ModuleNotFoundError: No module named '.tox'` error.

Of course one thing that still needs to happen, is that this needs to be tested in combination with https://github.com/plone/plone.app.content/pull/271.  But even then, when I run the 6.0 tests with both branches checked out, it fails in the same way as here in gh-actions.

It seems to work fine in practice though: when I fire up an instance and create a new Image and a new Page, they both get a normalised id based on the file name or the page title.

So I wonder if something is wrong in test setup, that some zcml is not loading, but I don't see what it would be.

**Comment by mauritsvanrees** [comment]
Okay, I kind-of see what is going on, but not completely.

In [`plone/app/dexterity/tests/namefromtitle.txt`](https://github.com/plone/plone.app.dexterity/pull/379/files#diff-ec34d1e4e6b16c629c4bf366ba961a93a8ab6687e1f38e8f8d67dc269abe3349R17) we have created a portal_type and added some behaviors.  At first this was `plone.app.content.interfaces.INameFromTitle`, which worked, but in this PR we of course change this to `plone.base.interfaces.INameFromTitle`.
This somehow does not work.  But the previous setting no longer works either.

The way to fix this in the test, is to use the named behavior `plone.namefromtitle`.  Tests then pass, case closed.

But the problem then remains: if there is a site that uses this behavior by interface, either the old or the new one, then it fails.

Maybe someone can come up with a combination that works, but I could not.  I think we need to postpone this PR and https://github.com/plone/plone.app.content/pull/271 until at least Plone 6.1, and maybe 7.0.

What might help, is one of the following, probably somewhere in `plone.behavior` or `plone.dexterity`:

* If someone sets the `behaviors` property of an FTI, automatically convert interfaces to named behaviors if available, and save this to the database.
* Do the same, but do this when reading the property.  Could be expensive as this is used a lot when reading attributes from a content type.  Possibly change it on-the-fly, but that would be a write-on-read.
* Have an upgrade step that goes through all FTIs and fixes this.  But this is one-time only and then an add-on could still use an interface name and then it fails again.

Wait, would `former_dotted_names` in the behavior registration help?  No, it does not.  I tried it like this:

```
  <!-- Title-to-id -->
  <plone:behavior
      name="plone.namefromtitle"
      title="Name from title"
      description="Automatically generate short URL name for content based on its initial title"
      provides="plone.base.interfaces.INameFromTitle"
      former_dotted_names="plone.app.content.interfaces.INameFromTitle plone.base.interfaces.INameFromTitle"
      />
```

Ah but this is used in [`lookup_behavior_registration`](https://github.com/plone/plone.behavior/blob/546ed0f0dfbff9ecc24a114625ba5a242fafe595/plone/behavior/registration.py#L72) which is only called when you go the the Types Control Panel and go to the Behaviors tab of a type.  And there it does not help either: when I have the interface in the behaviors in the ZMI, the `plone.nameformtitle` behavior is not checked in the Plone UI.

**Comment by mauritsvanrees** [comment]
@gforcada @davisagli We may need to revert the `plone.base` change: the `INameFromTitle` there has no effect if people use it, unless we merge these two PRs, but as explained I am currently against that...  What do you think?

I would be happy to be shown an error in my logic.

**Comment by mauritsvanrees** [comment]
I have created a PR to make `plone.app.content` a conditional dependency of `plone.app.dexterity`, so at least the circular dependency is broken: https://github.com/plone/plone.app.dexterity/pull/380

For the moment in Plone 6.0.8 we could revert `plone.base` to 1.1.4.

**Comment by davisagli** [comment]
@mauritsvanrees I think you are on the right track. Earlier I missed that the old interface location could be stored somewhere persistently.

There isn't much harm in leaving the INameFromTitle in plone.base, except for potential confusion. We could leave it there and update INameFromTitle in plone.app.content to extend it, so that we're at least moving in the intended direction.

**Comment by mauritsvanrees** [comment]
Closed in favour of PR #380.

**Pull request closed without merging**
