### PR TITLE
Use plone i18n domain

### PR DESCRIPTION
**Pull request by gforcada**
plone.app.dexterity is an official Plone core package,
thus their translations belong to plone.app.locales.

This commit removes the plone.app.dexterity domain and changes it for
plone.

This fixes:
https://github.com/plone/plone.app.dexterity/issues/158

Needs to be merged together with https://github.com/plone/plone.schemaeditor/pull/35

### CODE REVIEW

**Comment by jensens** [comment]
changelog entry would be good

**Comment by gforcada** [comment]
@jensens done

**Comment by vincentfretin** [comment]
refs https://github.com/plone/Products.CMFPlone/issues/983

**Comment by gforcada** [comment]
@jensens I did not merge this one myself because p.a.dexterity is also using plone.z3cform domain, which unfortunately is not on plone github org so we can not fix that as well... See https://github.com/plone/buildout.coredev/issues/139

**Comment by jensens** [comment]
i see, i'am fixing it at the moment. stay tuned

**Comment by jensens** [comment]
ok, fixed the bug with wrong imports that was left. That happens if I forget to run PR testing on jenkins :/

Anyways, where is the i18n domain in question used?

**Comment by gforcada** [comment]
Here: https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/browser/tabbed_forms.pt#L6

**Comment by jensens** [comment]
uh, ok, but we can deal with it on a separate PR, right?

**Comment by vincentfretin** [comment]
AFAICS you can use the plone domain in this template, there is no string in there and I expect all the dynamic components there to use their own domain.

**Pull request merged**
