### PR TITLE
Default to a 4K x 4K browser window in Robot tests

### PR DESCRIPTION
**Pull request by Rotonen**
I'm in the process of trying to unify Robot test setups and teardowns. This is a part of that effort.

In tandem with https://github.com/plone/plone.app.robotframework/pull/110
Closes https://github.com/plone/plone.app.dexterity/issues/292

### CODE REVIEW

**Comment by Rotonen** [comment]
Let's see if I'm lucky with 5.1:

@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Jenkins was out of space, but Gil has fixed it.

@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
